---
- name: Get MySQL APT key
  ansible.builtin.apt_key:
    keyserver: "{{ mysql_key_server }}"
    id: "{{ mysql_key_id }}"
    state: present
- name: Add MySQL repo to source list
  ansible.builtin.apt_repository:
    repo: "deb http://repo.mysql.com/apt/ubuntu/ {{ distro }} {{ mysql_series }}"
    state: present
- name: Install MySQL server
  ansible.builtin.apt:
    pkg:
      - mysql-server
      - python3-pip
      - python3-mysqldb # required to use 'mysql_db' module
    state: present
    update_cache: true
