---
- name: Configure Hetzner Cloud instance
  ansible.builtin.include_tasks: hcloud.yaml
  when: provider == 'hcloud'
# - name: Copy scripts
#   ansible.builtin.template:
#     src: setup-route.sh.j2
#     dest: /tmp/setup-route.sh
#     owner: root
#     group: root
#     mode: '0755'
# - name: Execute scripts
#   ansible.builtin.command:
#     cmd: /tmp/setup-route.sh
#     creates: /tmp/setup-route.sh.done
# - name: Copy persistent configuration
#   ansible.builtin.template:
#     src: network-setup.j2
#     dest: /etc/systemd/network/10-enp7s0.network
#     owner: root
#     group: root
#     mode: '0644'
# - name: Configure DNS servers
#   ansible.builtin.lineinfile:
#     path: /etc/systemd/resolved.conf
#     regexp: ^#DNS=
#     line: "DNS={{ dns_servers | default('8.8.8.8') }}"
