---
- name: Get MySQL APT key
  ansible.builtin.apt_key:
    keyserver: "{{ mysql_key_server }}"
    id: "{{ mysql_key_id }}"
    state: present
- name: Add MySQL repo to source list
  ansible.builtin.apt_repository:
    repo: "deb http://repo.mysql.com/apt/ubuntu/ {{ distro }} {{ mysql_series }}"
    state: present
- name: Install MySQL server
  ansible.builtin.apt:
    pkg:
      - mysql-server
      - python3-pip
      - python3-mysqldb # required to use 'mysql_db' module
    state: present
    update_cache: true
- name: Custom configuration
  ansible.builtin.template:
    src: 10-liftoff-mysql.cnf.j2
    dest: /etc/mysql/conf.d/10-liftoff-mysql.cnf
    mode: '0644'
- name: Restart Mysql service
  ansible.builtin.systemd:
    name: mysql
    state: restarted
- name: Copy root password script
  ansible.builtin.template:
    src: root-pass-conf.sql.j2
    dest: /tmp/root-pass-conf.sql
    mode: '0755'
- name: Change password for root user
  become: true
  ansible.builtin.command:
    cmd: sudo mysql < /tmp/root-pass-conf.sql
    creates: ~/root-pass-conf.sql.done
  register: change_root_password
  failed_when: change_root_password.rc != 0 and 'ERROR' in change_root_password.stderr
