name: Build pipeline
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  validate-configuration:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.calculate-version.outputs.version-string }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"
          terraform_wrapper: false
      - name: Check Terraform formatting
        run: terraform fmt -check -recursive .
        continue-on-error: false
      - name: Configure version information
        id: calculate-version
        if: ${{ github.event_name == 'push' }}
        uses: bitshifted/git-auto-semver@v1
        with:
          create_tag: true
          initial_version: 1.0.0
  # Create release
  create-release:
    if:  ${{ github.event_name == 'push' }}
    needs: validate-configuration
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          tag_name: v${{ needs.validate-configuration.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
            
